// LoopRoots.h -- GENERATED by tools/bake_loop_roots.cpp. DO NOT EDIT.
// Per-loop MEASURED root pitch (Hz) for the 130 v3 library loops, in
// bank/manifest order (Bank3 indices 78..207). DSP_BUILD.md section 1b:
// each tonal loop's true pitch is off +-36..45 cents from the 220 Hz
// bake nominal, so the engine must stretch by noteHz/rootHz using the
// loop's OWN measured root, not a fixed 220. Inharmonic loops (METAL_*
// and the MORPH ETHMETAL/METALAIR/VOXMETAL partners) keep 220.0 nominal
// (used as texture, not played melodically).
//
// Values are copied 1:1 from assets/library-src/loop_roots.json in the
// order of assets/library-src/manifest.json. Regenerate with:
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_loop_roots.cpp \
//     /Fe:tools\bin\bake_loop_roots.exe && tools\bin\bake_loop_roots.exe
#pragma once

namespace rompler::bank3 {

// 130 measured roots, manifest order (15 inharmonic loops pinned to 220.0).
inline constexpr float kLoopRoots[130] = {
    217.919000f, 218.434000f, 218.266000f, 221.413000f,
    217.181000f, 217.580000f, 220.477000f, 218.574000f,
    218.016000f, 218.925000f, 222.355000f, 218.583000f,
    221.426000f, 220.401000f, 221.101000f, 222.406000f,
    218.158000f, 219.256000f, 219.868000f, 219.892000f,
    218.645000f, 222.678000f, 218.748000f, 220.622000f,
    220.704000f, 219.319000f, 218.942000f, 221.203000f,
    220.292000f, 219.696000f, 218.669000f, 219.208000f,
    217.185000f, 221.730000f, 218.581000f, 220.659000f,
    216.978000f, 219.424000f, 223.413000f, 220.339000f,
    219.975000f, 220.545000f, 220.696000f, 218.636000f,
    222.019000f, 222.031000f, 222.090000f, 222.694000f,
    219.730000f, 222.151000f, 214.912000f, 222.907000f,
    219.734000f, 218.627000f, 219.972000f, 220.895000f,
    219.788000f, 220.186000f, 222.280000f, 219.363000f,
    217.907000f, 220.111000f, 220.463000f, 218.291000f,
    221.888000f, 218.079000f, 221.915000f, 219.007000f,
    221.822000f, 219.710000f, 220.713000f, 219.936000f,
    220.393000f, 219.779000f, 220.544000f, 219.332000f,
    217.946000f, 219.956000f, 221.415000f, 220.904000f,
    222.016000f, 220.140000f, 221.970000f, 219.874000f,
    219.946000f, 220.771000f, 218.150000f, 222.757000f,
    216.454000f, 221.026000f, 218.786000f, 217.677000f,
    220.153000f, 218.188000f, 220.138000f, 223.489000f,
    221.857000f, 220.367000f, 218.199000f, 221.001000f,
    219.870000f, 219.379000f, 218.169000f, 218.614000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.504000f, 220.544000f, 219.443000f, 220.826000f,
    220.000000f, 219.201000f, 219.262000f, 220.235000f,
    221.764000f, 220.000000f, 217.917000f, 221.586000f,
    220.000000f, 222.000000f,
};

} // namespace rompler::bank3
