// LoopRoots.h -- GENERATED by tools/bake_loop_roots.cpp. DO NOT EDIT.
// Per-loop MEASURED root pitch (Hz) for the 130 v3 library loops, in
// bank/manifest order (Bank3 indices 78..207). DSP_BUILD.md section 1b:
// each tonal loop's true pitch is off +-36..45 cents from the 220 Hz
// bake nominal, so the engine must stretch by noteHz/rootHz using the
// loop's OWN measured root, not a fixed 220. Inharmonic loops (METAL_*
// and the MORPH ETHMETAL/METALAIR/VOXMETAL partners) keep 220.0 nominal
// (used as texture, not played melodically).
//
// Values are copied 1:1 from assets/library-src/loop_roots.json in the
// order of assets/library-src/manifest.json. Regenerate with:
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_loop_roots.cpp \
//     /Fe:tools\bin\bake_loop_roots.exe && tools\bin\bake_loop_roots.exe
#pragma once

namespace rompler::bank3 {

// 130 measured roots, manifest order (15 inharmonic loops pinned to 220.0).
inline constexpr float kLoopRoots[130] = {
    219.093000f, 220.495000f, 218.154000f, 219.730000f,
    220.351000f, 219.671000f, 219.755000f, 218.817000f,
    221.995000f, 221.721000f, 217.192000f, 222.056000f,
    220.932000f, 217.680000f, 220.860000f, 220.498000f,
    217.074000f, 218.661000f, 222.517000f, 223.190000f,
    217.969000f, 216.879000f, 223.628000f, 217.808000f,
    220.853000f, 223.077000f, 222.286000f, 221.614000f,
    223.970000f, 218.511000f, 221.871000f, 221.623000f,
    219.107000f, 218.049000f, 220.708000f, 220.487000f,
    219.488000f, 218.953000f, 219.543000f, 220.175000f,
    219.361000f, 219.151000f, 219.796000f, 219.840000f,
    222.265000f, 220.691000f, 220.118000f, 219.182000f,
    216.877000f, 220.266000f, 223.599000f, 222.927000f,
    215.435000f, 220.041000f, 220.337000f, 219.515000f,
    219.014000f, 218.456000f, 220.859000f, 219.714000f,
    219.899000f, 219.560000f, 219.741000f, 221.611000f,
    217.539000f, 223.781000f, 220.374000f, 218.962000f,
    221.710000f, 221.759000f, 219.478000f, 217.798000f,
    219.154000f, 219.258000f, 223.414000f, 219.870000f,
    218.834000f, 216.980000f, 217.519000f, 219.385000f,
    225.777000f, 218.392000f, 218.922000f, 218.125000f,
    222.512000f, 221.484000f, 219.021000f, 219.914000f,
    221.917000f, 218.493000f, 218.477000f, 220.066000f,
    221.662000f, 222.890000f, 221.807000f, 220.577000f,
    218.942000f, 218.247000f, 220.799000f, 221.929000f,
    218.695000f, 220.506000f, 221.967000f, 220.513000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    218.672000f, 220.516000f, 221.298000f, 222.662000f,
    220.000000f, 220.207000f, 219.828000f, 221.910000f,
    220.354000f, 220.000000f, 221.635000f, 219.258000f,
    220.000000f, 218.786000f,
};

} // namespace rompler::bank3
