// LoopRoots.h -- GENERATED by tools/bake_loop_roots.cpp. DO NOT EDIT.
// Per-loop root pitch (Hz) for the 130 v3 library loops, in bank/manifest
// order (Bank3 indices 78..207). The v3 library is SYNTHESIZED at a fixed
// 220 Hz nominal (bake_final.py: root=220.0, 'no rootHz correction, no
// pitch-lock warp'), so every loop's root is 220.0 -- the engine stretch
// noteHz/rootHz then plays each loop in tune. (The pre-2.5.1 header held
// stale v2-measured roots off +-up to ~45 cents; playing v3 audio through
// them detuned every tonal loop ~+13 cents sharp -- fixed here.)
//
// Values are copied 1:1 from assets/library-src/loop_roots.json in the
// order of assets/library-src/manifest.json. Regenerate with:
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_loop_roots.cpp \
//     /Fe:tools\bin\bake_loop_roots.exe && tools\bin\bake_loop_roots.exe
#pragma once

namespace rompler::bank3 {

// 130 roots, manifest order -- all 220.0 (v3 synthesized at 220 nominal).
// (130 entries at 220.0)
inline constexpr float kLoopRoots[130] = {
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f, 220.000000f, 220.000000f,
    220.000000f, 220.000000f,
};

} // namespace rompler::bank3
