// bake_loops_header.cpp -- packs assets/loops/*.wav (the bake_loops.py
// output, 16-bit mono 44.1k seamless full-buffer loops) into
// dsp/bank/LoopBankData.h as 12-bit-left-justified constexpr int16 arrays
// (round-to-nearest 12-bit, low nibble zero by construction -- the bank
// invariant). This is the DSP_BUILD.md section 1 "--emit-header mode",
// implemented as a C++ tool per the no-python house rule.
//
// Build + run (after vcvars64.bat), from C:\the-dreamer:
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_loops_header.cpp
//     /Fo:tests\bin\ /Fe:tests\bin\bake_loops_header.exe
//   tests\bin\bake_loops_header.exe assets\loops dsp\bank\LoopBankData.h
//
// Loop order below = bake_loops.py recipe order (LOCKED: wave-choice index
// depends on it). All loops: category "Ens", rootHz 220.0, loopStart 0.

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>

static const char* kLoopNames[] = {
    // v1 batch (bake_loops.py order) -- indices 0..15 held STABLE
    "STRINGBOX_ENS", "CATHEDRAL", "CHOIR_MORPH", "GLASS_CHOIR",
    "SOLINA_DREAM", "CELLO_SECTION", "THEREMIN_SWARM", "DARK_BREATH",
    "FM_HALO", "SPECTRAL_TIDE", "SAW_CLOUD", "TANNERIN_GHOST",
    "ORGAN_MASS", "VOICE_OF_STEEL", "BELL_GARDEN", "ACID_MIRAGE",
    // v2 batch2 (bake_loops2.py order) -- appended 16..25
    "ETHEREAL_CHOIR", "OPERA_VIOLA", "CELLO_CHOIR", "STEEL_CHOIR",
    "CHROME_VOICES", "ORACLE", "STRING_OCTAVES", "GHOST_ORCHESTRA",
    "VIOLIN_SERAPH", "CATHEDRAL_STRINGS",
};
static const int kNumLoops = 26;

// minimal RIFF/WAVE reader: 16-bit mono PCM, chunk-walks to "data"
static bool readWav(const std::string& path, std::vector<int16_t>& out, uint32_t& sr) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) return false;
    char id[4]; uint32_t sz;
    if (std::fread(id, 1, 4, f) != 4 || std::memcmp(id, "RIFF", 4)) { std::fclose(f); return false; }
    std::fread(&sz, 4, 1, f);
    std::fread(id, 1, 4, f);
    if (std::memcmp(id, "WAVE", 4)) { std::fclose(f); return false; }
    uint16_t fmt = 0, ch = 0, bits = 0;
    sr = 0;
    while (std::fread(id, 1, 4, f) == 4 && std::fread(&sz, 4, 1, f) == 1) {
        if (!std::memcmp(id, "fmt ", 4)) {
            uint16_t ba; uint32_t br;
            std::fread(&fmt, 2, 1, f); std::fread(&ch, 2, 1, f);
            std::fread(&sr, 4, 1, f);  std::fread(&br, 4, 1, f);
            std::fread(&ba, 2, 1, f);  std::fread(&bits, 2, 1, f);
            if (sz > 16) std::fseek(f, (long)sz - 16, SEEK_CUR);
        } else if (!std::memcmp(id, "data", 4)) {
            out.resize(sz / 2);
            std::fread(out.data(), 2, out.size(), f);
            std::fclose(f);
            return fmt == 1 && ch == 1 && bits == 16;
        } else {
            std::fseek(f, (long)(sz + (sz & 1)), SEEK_CUR);
        }
    }
    std::fclose(f);
    return false;
}

int main(int argc, char** argv) {
    const std::string dir = argc > 1 ? argv[1] : "assets\\loops";
    const char* outPath   = argc > 2 ? argv[2] : "dsp\\bank\\LoopBankData.h";

    FILE* o = std::fopen(outPath, "wb");
    if (!o) { std::printf("cannot open %s\n", outPath); return 1; }
    std::fprintf(o,
        "// Auto-generated by tools/bake_loops_header.cpp from assets/loops/*.wav\n"
        "// (bake_loops.py output) -- DO NOT EDIT. 12-bit left-justified int16\n"
        "// (low nibble zero), mono 44.1k, seamless full-buffer loops, root 220 Hz.\n"
        "#pragma once\n#include <cstdint>\n\nnamespace rompler::bank::loopdata {\n\n");

    uint64_t total = 0;
    std::vector<uint32_t> lengths;
    for (int i = 0; i < kNumLoops; ++i) {
        std::vector<int16_t> s;
        uint32_t sr = 0;
        const std::string path = dir + "\\" + kLoopNames[i] + ".wav";
        if (!readWav(path, s, sr) || sr != 44100 || s.empty()) {
            std::printf("FAILED reading %s (sr=%u n=%zu)\n", path.c_str(), sr, s.size());
            std::fclose(o);
            return 1;
        }
        lengths.push_back((uint32_t)s.size());
        total += s.size();
        std::fprintf(o, "inline constexpr int16_t lp_%s[%u] = {",
                     kLoopNames[i], (unsigned)s.size());
        for (size_t n = 0; n < s.size(); ++n) {
            if (n % 12 == 0) std::fprintf(o, "\n  ");
            int q = (int)std::lround(s[n] / 16.0);          // 12-bit round-to-nearest
            if (q > 2047) q = 2047; if (q < -2048) q = -2048;
            std::fprintf(o, "%6d,", (int16_t)(q * 16));     // left-justified
        }
        std::fprintf(o, "\n};\n\n");
        std::printf("%-16s %7u samples\n", kLoopNames[i], (unsigned)s.size());
    }

    std::fprintf(o, "struct LoopEntry { const char* name; const int16_t* samples; uint32_t length; };\n");
    std::fprintf(o, "inline constexpr LoopEntry kLoops[%d] = {\n", kNumLoops);
    for (int i = 0; i < kNumLoops; ++i)
        std::fprintf(o, "  { \"%s\", lp_%s, %uu },\n", kLoopNames[i], kLoopNames[i], (unsigned)lengths[(size_t)i]);
    std::fprintf(o, "};\n\n} // namespace rompler::bank::loopdata\n");
    std::fclose(o);
    std::printf("total %llu samples (%.2f MB as int16)\n",
                (unsigned long long)total, (double)total * 2.0 / 1048576.0);
    return 0;
}
