// bake_wave_norm.cpp -- D11 (UX_DSP_TASKS): per-wave PLAYBACK loudness table.
//
// The bank browses badly because loops/cycles sit at wildly different levels.
// Rather than renormalize the bank samples (CLAUDE.md rule 3 forbids it, and
// the v2 cycle bank is read-only + bit-parity tested), we bake a per-wave GAIN
// that equalizes loudness AT PLAYBACK -- the stored bytes are never touched.
//
//   CYCLE + LOOP -> gain = targetRms / measuredRms   (target -14 dBFS RMS),
//                   clamped to [1/8, 8] so a near-silent wave is not blown up.
//   ONESHOT (HIT) -> gain = 1.0: hits are already PEAK-normalized to 0.98 at
//                   bake time and must keep their transient punch (D11).
//
// Emits dsp/glue/WaveNormTable.h: inline constexpr float kWaveNormGain[N].
// Deterministic; no python (house C++-tool convention).
//
// Build (after vcvars64), from C:\the-dreamer:
//   cl /nologo /std:c++17 /O2 /EHsc /D_USE_MATH_DEFINES /I. ^
//      tools\bake_wave_norm.cpp /Fo:tools\bin\ /Fe:tools\bin\bake_wave_norm.exe
//   tools\bin\bake_wave_norm.exe            (writes dsp\glue\WaveNormTable.h)

#include <cstdio>
#include <cmath>
#include <cstdint>
#include "dsp/bank/Bank3.h"

int main(int argc, char** argv) {
    using namespace rompler::bank3;
    const char* outPath = argc > 1 ? argv[1] : "dsp\\glue\\WaveNormTable.h";

    const double targetRms = std::pow(10.0, -14.0 / 20.0);   // -14 dBFS = 0.19953
    const double gMin = 0.125, gMax = 8.0;

    FILE* f = std::fopen(outPath, "wb");
    if (!f) { std::printf("ERROR: cannot open %s\n", outPath); return 1; }

    std::fprintf(f,
        "// WaveNormTable.h -- GENERATED by tools/bake_wave_norm.cpp (D11).\n"
        "// Per-wave playback loudness gain: CYCLE/LOOP normalized to -14 dBFS RMS,\n"
        "// HIT (OneShot) left at 1.0 (already peak-normalized). Bank bytes are NOT\n"
        "// modified (CLAUDE.md rule 3). Applied to the oscillator sum in DreamVoice.\n"
        "#pragma once\n\n"
        "namespace dreamer {\n\n"
        "inline constexpr int   kWaveNormCount = %d;\n"
        "inline constexpr float kWaveNormGain[%d] = {\n", kNumWaveforms, kNumWaveforms);

    for (int i = 0; i < kNumWaveforms; ++i) {
        const auto& w = kWaveforms[(size_t)i];
        double gain = 1.0;
        if (w.type != WaveType::OneShot) {
            double sumsq = 0.0;
            const uint32_t n = w.length;
            for (uint32_t s = 0; s < n; ++s) {
                const double x = (double)w.samples[s] * (1.0 / 32768.0);
                sumsq += x * x;
            }
            const double rms = n > 0 ? std::sqrt(sumsq / (double)n) : 0.0;
            gain = rms > 1e-9 ? targetRms / rms : 1.0;
            if (gain < gMin) gain = gMin; else if (gain > gMax) gain = gMax;
        }
        std::fprintf(f, "    %.6ff,%s", (float)gain,
                     ((i % 6) == 5 || i == kNumWaveforms - 1) ? "\n" : "");
    }
    std::fprintf(f, "};\n\n} // namespace dreamer\n");
    std::fclose(f);
    std::printf("wrote %s (%d gains, target -14 dBFS RMS)\n", outPath, kNumWaveforms);
    return 0;
}
