// bake_loop_roots.cpp -- emit dsp/bank/LoopRoots.h from the shipped library
// metadata (DSP_BUILD.md section 1b: per-loop measured rootHz).
//
// Inputs (read as flat JSON, no JSON lib on this VM by design):
//   assets/library-src/manifest.json    -- JSON array of the 130 loop names in
//                                           BANK ORDER (index 78..207 of Bank3).
//   assets/library-src/loop_roots.json   -- flat object { "LOOP_NAME": hz, ... }
//                                           of MEASURED root pitches. METAL_* and
//                                           the inharmonic MORPH partners
//                                           (ETHMETAL/METALAIR/VOXMETAL) are 220.0
//                                           nominal (texture, not played melodically).
//
// Output:
//   dsp/bank/LoopRoots.h -- inline constexpr float kLoopRoots[130] in manifest
//                           order, one value per loop, 1:1 with the JSON.
//
// The values come STRAIGHT from loop_roots.json in manifest.json order; the tool
// aborts if any manifest name is missing a root (so the header can never drift
// out of sync with the data). This tool does NOT touch the 102 MB sample header.
//
// Build + run (from C:\the-dreamer, after vcvars64):
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_loop_roots.cpp /Fe:tools\bin\bake_loop_roots.exe
//   tools\bin\bake_loop_roots.exe
//
// C++17, host tool (not shipped, not RT).

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>
#include <unordered_map>

static std::string slurp(const char* path) {
    FILE* f = std::fopen(path, "rb");
    if (!f) { std::fprintf(stderr, "cannot open %s\n", path); std::exit(2); }
    std::string s;
    char buf[4096];
    size_t n;
    while ((n = std::fread(buf, 1, sizeof buf, f)) > 0) s.append(buf, n);
    std::fclose(f);
    return s;
}

// Pull every "quoted" token in appearance order (manifest is a flat string array).
static std::vector<std::string> parseStringArray(const std::string& j) {
    std::vector<std::string> out;
    size_t i = 0;
    while (i < j.size()) {
        if (j[i] == '"') {
            size_t e = j.find('"', i + 1);
            if (e == std::string::npos) break;
            out.emplace_back(j.substr(i + 1, e - i - 1));
            i = e + 1;
        } else {
            ++i;
        }
    }
    return out;
}

// Parse a flat { "KEY": number, ... } object into a name->value map.
static std::unordered_map<std::string, double> parseFlatObject(const std::string& j) {
    std::unordered_map<std::string, double> m;
    size_t i = 0;
    while (i < j.size()) {
        if (j[i] != '"') { ++i; continue; }
        size_t e = j.find('"', i + 1);
        if (e == std::string::npos) break;
        std::string key = j.substr(i + 1, e - i - 1);
        size_t c = j.find(':', e + 1);
        if (c == std::string::npos) break;
        // skip whitespace to the number
        size_t p = c + 1;
        while (p < j.size() && (j[p] == ' ' || j[p] == '\t' || j[p] == '\n' || j[p] == '\r')) ++p;
        char* end = nullptr;
        double v = std::strtod(j.c_str() + p, &end);
        m[key] = v;
        i = (size_t)(end - j.c_str());
    }
    return m;
}

int main() {
    const std::string manifest = slurp("assets/library-src/manifest.json");
    const std::string roots    = slurp("assets/library-src/loop_roots.json");

    const std::vector<std::string> names = parseStringArray(manifest);
    const std::unordered_map<std::string, double> rootMap = parseFlatObject(roots);

    if (names.size() != 130) {
        std::fprintf(stderr, "manifest has %zu names, expected 130\n", names.size());
        return 3;
    }

    // Build the value list in manifest order; abort on any missing root.
    std::vector<double> vals;
    vals.reserve(130);
    int nInharmonic = 0;
    for (const auto& n : names) {
        auto it = rootMap.find(n);
        if (it == rootMap.end()) {
            std::fprintf(stderr, "missing root for loop '%s'\n", n.c_str());
            return 4;
        }
        vals.push_back(it->second);
        if (it->second == 220.0) ++nInharmonic;
    }

    FILE* o = std::fopen("dsp/bank/LoopRoots.h", "wb");
    if (!o) { std::fprintf(stderr, "cannot write dsp/bank/LoopRoots.h\n"); return 5; }

    std::fprintf(o,
        "// LoopRoots.h -- GENERATED by tools/bake_loop_roots.cpp. DO NOT EDIT.\n"
        "// Per-loop root pitch (Hz) for the 130 v3 library loops, in bank/manifest\n"
        "// order (Bank3 indices 78..207). The v3 library is SYNTHESIZED at a fixed\n"
        "// 220 Hz nominal (bake_final.py: root=220.0, 'no rootHz correction, no\n"
        "// pitch-lock warp'), so every loop's root is 220.0 -- the engine stretch\n"
        "// noteHz/rootHz then plays each loop in tune. (The pre-2.5.1 header held\n"
        "// stale v2-measured roots off +-up to ~45 cents; playing v3 audio through\n"
        "// them detuned every tonal loop ~+13 cents sharp -- fixed here.)\n"
        "//\n"
        "// Values are copied 1:1 from assets/library-src/loop_roots.json in the\n"
        "// order of assets/library-src/manifest.json. Regenerate with:\n"
        "//   cl /nologo /std:c++17 /O2 /EHsc tools\\bake_loop_roots.cpp \\\n"
        "//     /Fe:tools\\bin\\bake_loop_roots.exe && tools\\bin\\bake_loop_roots.exe\n"
        "#pragma once\n\n"
        "namespace rompler::bank3 {\n\n"
        "// 130 roots, manifest order -- all 220.0 (v3 synthesized at 220 nominal).\n"
        "// (%d entries at 220.0)\n"
        "inline constexpr float kLoopRoots[130] = {\n", nInharmonic);

    for (size_t i = 0; i < vals.size(); ++i) {
        if (i % 4 == 0) std::fprintf(o, "    ");
        std::fprintf(o, "%.6ff,", vals[i]);
        std::fprintf(o, ((i % 4 == 3) || i + 1 == vals.size()) ? "\n" : " ");
    }

    std::fprintf(o,
        "};\n\n"
        "} // namespace rompler::bank3\n");
    std::fclose(o);

    std::printf("wrote dsp/bank/LoopRoots.h: 130 roots (%d inharmonic == 220.0)\n", nInharmonic);
    // Echo a few for eyeball verification.
    std::printf("  [0] %-16s %.3f\n", names[0].c_str(), vals[0]);
    std::printf("  [4] %-16s %.3f (pitch-test loop)\n", names[4].c_str(), vals[4]);
    std::printf("  [104] %-14s %.3f (first METAL)\n", names[104].c_str(), vals[104]);
    return 0;
}
