// bake_shapers.cpp -- generates dsp/glue/ShaperTables.h (the "01/W trick"
// waveshaper LUTs, FEATURES.md section 2).
//
// This is the C++ stand-in for the spec's bake_shapers.py: the VM keeps no
// Python by design (CLAUDE-WORKFLOW section 2), so the bake runs through
// cl.exe instead. Deterministic double math; regenerating always produces
// byte-identical output.
//
// Build + run (after vcvars64.bat), from C:\the-dreamer:
//   cl /nologo /std:c++17 /O2 /EHsc /D_USE_MATH_DEFINES tools\bake_shapers.cpp
//     /Fo:tests\bin\ /Fe:tests\bin\bake_shapers.exe
//   tests\bin\bake_shapers.exe dsp\glue\ShaperTables.h
//
// Tables: 1024-entry int16, 12-bit quantized exactly like the wave bank
// (value = round(y * 2047) << 4, so the low nibble is zero by construction).
// Set: SOFT FOLD, HARD FOLD, SINE FOLD, ASYM, DRIVE (OFF is not a table).

#include <cstdio>
#include <cstdint>
#include <cmath>
#include <string>
#include <vector>

static const int kLen = 1024;

// reflect v into [-1, 1] (triangle fold)
static double fold(double v) {
    while (v > 1.0 || v < -1.0) {
        if (v > 1.0)  v = 2.0 - v;
        if (v < -1.0) v = -2.0 - v;
    }
    return v;
}

struct Table { const char* cname; const char* label; std::vector<double> y; };

int main(int argc, char** argv) {
    const char* outPath = argc > 1 ? argv[1] : "dsp\\glue\\ShaperTables.h";

    std::vector<Table> tables = {
        { "kSoftFold", "SOFT FOLD", {} },
        { "kHardFold", "HARD FOLD", {} },
        { "kSineFold", "SINE FOLD", {} },
        { "kAsym",     "ASYM",      {} },
        { "kDrive",    "DRIVE",     {} },
    };

    for (int i = 0; i < kLen; ++i) {
        const double x = (i / (double)(kLen - 1)) * 2.0 - 1.0;   // [-1, 1]
        tables[0].y.push_back(std::sin(1.25 * M_PI * x));         // soft single fold
        tables[1].y.push_back(fold(1.8 * x));                     // hard triangle fold
        tables[2].y.push_back(std::sin(2.0 * M_PI * x));          // through-zero sine fold
        tables[3].y.push_back(std::tanh(2.5 * x + 0.5 * x * x));  // asymmetric (even term)
        tables[4].y.push_back(std::tanh(3.0 * x) / std::tanh(3.0)); // drive
    }

    // peak-normalize each table to 0.9995 (bank convention)
    for (auto& t : tables) {
        double peak = 0.0;
        for (double v : t.y) peak = std::fmax(peak, std::fabs(v));
        const double g = peak > 0.0 ? 0.9995 / peak : 1.0;
        for (auto& v : t.y) v *= g;
    }

    FILE* f = std::fopen(outPath, "wb");
    if (!f) { std::printf("cannot open %s\n", outPath); return 1; }
    std::fprintf(f,
        "// Auto-generated by tools/bake_shapers.cpp -- DO NOT EDIT.\n"
        "// Waveshaper transfer tables (FEATURES.md section 2, the 01/W trick).\n"
        "// 1024 x int16, 12-bit quantized (round(y*2047)<<4 -- low nibble zero).\n"
        "#pragma once\n#include <cstdint>\n\n"
        "namespace dreamer::shapers {\n\n"
        "inline constexpr int kTableLen = %d;\n\n", kLen);

    for (auto& t : tables) {
        std::fprintf(f, "// %s\ninline constexpr int16_t %s[kTableLen] = {", t.label, t.cname);
        for (int i = 0; i < kLen; ++i) {
            if (i % 12 == 0) std::fprintf(f, "\n    ");
            const int q = (int)std::lround(t.y[(size_t)i] * 2047.0);
            std::fprintf(f, "%6d,", (int16_t)(q << 4));
        }
        std::fprintf(f, "\n};\n\n");
    }

    std::fprintf(f,
        "// index = shape_type - 1 (0 = OFF has no table)\n"
        "inline constexpr const int16_t* kTables[5] = {\n"
        "    kSoftFold, kHardFold, kSineFold, kAsym, kDrive,\n};\n\n"
        "} // namespace dreamer::shapers\n");
    std::fclose(f);
    std::printf("wrote %s (%d tables x %d entries)\n", outPath, (int)tables.size(), kLen);
    return 0;
}
