// bake_shots_header.cpp -- packs assets/shots/*.wav (the v3 sound-library
// deliverable: 10 HIT one-shot transients, 16-bit mono 44.1k PCM) into
// dsp/bank/ShotBankData.h as 12-bit-left-justified int16 arrays (round-to-
// nearest 12-bit, low nibble zero -- the bank invariant). This REPLACES the
// old synthesizing bake_shots.cpp with a WAV->header baker (readWav +
// requant path adapted from bake_loops_header.cpp). No-python house rule.
//
// Build + run (after vcvars64.bat), from C:\the-dreamer:
//   cl /nologo /std:c++17 /O2 /EHsc tools\bake_shots_header.cpp
//     /Fo:tests\bin\ /Fe:tests\bin\bake_shots_header.exe
//   tests\bin\bake_shots_header.exe assets\shots dsp\bank\ShotBankData.h
//
// Shot order below is LOCKED (wave-choice param index depends on it). All
// shots: category "Hit", rootHz 220.0 (Bank3 sets that).

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>

// LOCKED order = the 10 delivered HIT one-shots.
static const char* kShotNames[] = {
    "HIT_AIR_SWELL", "HIT_BELL_PING", "HIT_BREATH", "HIT_CHIFF", "HIT_CLICK",
    "HIT_MALLET", "HIT_NOISE_HIT", "HIT_PLUCK", "HIT_THUMP", "HIT_TINE_TICK",
};
static const int kNumShots = (int)(sizeof(kShotNames) / sizeof(kShotNames[0]));

// minimal RIFF/WAVE reader: 16-bit mono PCM, chunk-walks to "data"
static bool readWav(const std::string& path, std::vector<int16_t>& out, uint32_t& sr) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) return false;
    char id[4]; uint32_t sz;
    if (std::fread(id, 1, 4, f) != 4 || std::memcmp(id, "RIFF", 4)) { std::fclose(f); return false; }
    std::fread(&sz, 4, 1, f);
    std::fread(id, 1, 4, f);
    if (std::memcmp(id, "WAVE", 4)) { std::fclose(f); return false; }
    uint16_t fmt = 0, ch = 0, bits = 0;
    sr = 0;
    while (std::fread(id, 1, 4, f) == 4 && std::fread(&sz, 4, 1, f) == 1) {
        if (!std::memcmp(id, "fmt ", 4)) {
            uint16_t ba; uint32_t br;
            std::fread(&fmt, 2, 1, f); std::fread(&ch, 2, 1, f);
            std::fread(&sr, 4, 1, f);  std::fread(&br, 4, 1, f);
            std::fread(&ba, 2, 1, f);  std::fread(&bits, 2, 1, f);
            if (sz > 16) std::fseek(f, (long)sz - 16, SEEK_CUR);
        } else if (!std::memcmp(id, "data", 4)) {
            out.resize(sz / 2);
            std::fread(out.data(), 2, out.size(), f);
            std::fclose(f);
            return fmt == 1 && ch == 1 && bits == 16;
        } else {
            std::fseek(f, (long)(sz + (sz & 1)), SEEK_CUR);
        }
    }
    std::fclose(f);
    return false;
}

int main(int argc, char** argv) {
    const std::string dir = argc > 1 ? argv[1] : "assets\\shots";
    const char* outPath   = argc > 2 ? argv[2] : "dsp\\bank\\ShotBankData.h";

    FILE* o = std::fopen(outPath, "wb");
    if (!o) { std::printf("cannot open %s\n", outPath); return 1; }
    std::fprintf(o,
        "// Auto-generated by tools/bake_shots_header.cpp from assets/shots/*.wav\n"
        "// (v3 sound-library deliverable: 10 HIT one-shots) -- DO NOT EDIT.\n"
        "// 12-bit left-justified int16 (low nibble zero), mono 44.1k, root 220 Hz.\n"
        "// Order LOCKED. Sample arrays `inline const` (not constexpr); kShots\n"
        "// stores addresses only.\n"
        "#pragma once\n#include <cstdint>\n\nnamespace rompler::bank::shotdata {\n\n");

    uint64_t total = 0;
    std::vector<uint32_t> lengths;
    for (int i = 0; i < kNumShots; ++i) {
        std::vector<int16_t> s;
        uint32_t sr = 0;
        const std::string path = dir + "\\" + kShotNames[i] + ".wav";
        if (!readWav(path, s, sr) || sr != 44100 || s.empty()) {
            std::printf("FAILED reading %s (sr=%u n=%zu)\n", path.c_str(), sr, s.size());
            std::fclose(o);
            return 1;
        }
        lengths.push_back((uint32_t)s.size());
        total += s.size();
        std::fprintf(o, "inline const int16_t sh_%s[%u] = {",
                     kShotNames[i], (unsigned)s.size());
        for (size_t n = 0; n < s.size(); ++n) {
            if (n % 12 == 0) std::fprintf(o, "\n  ");
            int q = (int)std::lround(s[n] / 16.0);          // 12-bit round-to-nearest
            if (q > 2047) q = 2047; if (q < -2048) q = -2048;
            std::fprintf(o, "%6d,", (int16_t)(q * 16));     // left-justified
        }
        std::fprintf(o, "\n};\n\n");
        std::printf("%-16s Hit %7u samples (%.0f ms)\n", kShotNames[i],
                    (unsigned)s.size(), s.size() / 44.100);
    }

    std::fprintf(o, "struct ShotEntry { const char* name; const char* category; const int16_t* samples; uint32_t length; };\n");
    std::fprintf(o, "inline constexpr ShotEntry kShots[%d] = {\n", kNumShots);
    for (int i = 0; i < kNumShots; ++i)
        std::fprintf(o, "  { \"%s\", \"Hit\", sh_%s, %uu },\n",
                     kShotNames[i], kShotNames[i], (unsigned)lengths[(size_t)i]);
    std::fprintf(o, "};\n\n} // namespace rompler::bank::shotdata\n");
    std::fclose(o);
    std::printf("total %llu samples (%.2f MB as int16), %d shots\n",
                (unsigned long long)total, (double)total * 2.0 / 1048576.0, kNumShots);
    return 0;
}
